baseurl = "https://9jacovidmonitor.ga"
languageCode = "en-us"
theme = "terminal"
paginate = 5

[params]
  contentTypeName = "post"
  themeColor = "green"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    title = "9jaCovidMonitor"
    subtitle = "A simple, terminal for monitoring covid19 activities in Nigeria."
    keywords = "9jaCovidMonitorTerminal,9ja,Covid,Monitor,Terminal"
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "9jaCovidMonitor"
      logoHomeLink = "/"

    # [languages.en.menu]
    #   [[languages.en.menu.main]]
    #     identifier = "about"
    #     name = "About"
    #     url = "/about"
    #   [[languages.en.menu.main]]
    #     identifier = "showcase"
    #     name = "Showcase"
    #     url = "/showcase"
    #  [[languages.en.menu.main]]
    #     identifier = "video"
    #     name = "Video"
    #     url = "/video"
